# -*- coding: utf-8 -*-
"""BFS vs DFS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13blUe3_H92Y9eXnTzqi3L5cvWS1OlREX
"""

import random
import time
import pandas as pd
import matplotlib.pyplot as plt
from collections import deque

# -------- Tree Node --------
class Node:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None


# -------- Build Binary Tree (Level Order) --------
def build_tree(arr):
    if not arr:
        return None

    root = Node(arr[0])
    queue = deque([root])
    i = 1

    while i < len(arr):
        current = queue.popleft()

        if i < len(arr):
            current.left = Node(arr[i])
            queue.append(current.left)
            i += 1

        if i < len(arr):
            current.right = Node(arr[i])
            queue.append(current.right)
            i += 1

    return root


# -------- BFS --------
def bfs(root, goal):
    queue = deque([root])

    while queue:
        node = queue.popleft()

        if node.value == goal:
            return True

        if node.left:
            queue.append(node.left)
        if node.right:
            queue.append(node.right)

    return False


# -------- DFS --------
def dfs(root, goal):
    stack = [root]

    while stack:
        node = stack.pop()

        if node.value == goal:
            return True

        if node.right:
            stack.append(node.right)
        if node.left:
            stack.append(node.left)

    return False


# -------- Main Experiment --------
sizes = [1000, 40000, 80000, 200000, 1000000]

results = []

for size in sizes:
    print(f"Processing size: {size}")

    # Generate unique random numbers
    data = random.sample(range(size * 10), size)

    # Build tree
    root = build_tree(data)

    # Goal
    goal = data[size - 220]

    # BFS Time
    start = time.time()
    bfs(root, goal)
    bfs_time = time.time() - start

    # DFS Time
    start = time.time()
    dfs(root, goal)
    dfs_time = time.time() - start

    results.append([size, bfs_time, dfs_time])


# -------- DataFrame --------
df = pd.DataFrame(results, columns=["Tree Size", "BFS Time", "DFS Time"])
print(df)


# -------- Plot --------
df.plot(x="Tree Size", kind="bar")
plt.ylabel("Time (seconds)")
plt.title("BFS vs DFS Time Comparison")
plt.show()