# -*- coding: utf-8 -*-
"""DFS_Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QWRc9I47S4TZCSdzn503sYn9iyzvTgPJ
"""

# Using a Python dictionary to act as an adjacency list
graph = {
    '5' : ['3','7'],
    '3' : ['2', '4'],
    '7' : ['8'],
    '2' : [],
    '4' : ['8'],
    '8' : []
}

def dfs_iterative(graph, start_node):
    visited = set()   # Set to keep track of visited nodes
    stack = [start_node]  # Step 1: Put start vertex on top of stack

    print("Following is the Depth-First Search:")

    # Step 4: Repeat until stack is empty
    while stack:
        # Step 2: Take the top item from the stack
        vertex = stack.pop()

        if vertex not in visited:
            print(vertex, end=" ")
            visited.add(vertex) # Add to visited list

            # Step 3: Create list of adjacent nodes
            # We reverse the neighbors so they are processed in the same
            # order as the recursive version (5 -> 3 -> 2...)
            for neighbour in reversed(graph[vertex]):
                if neighbour not in visited:
                    stack.append(neighbour)

# Driver Code
dfs_iterative(graph, '5')

from collections import defaultdict

# This class represents a directed graph using adjacency list representation
class Graph:
    # Constructor
    def __init__(self):
        # default dictionary to store graph
        self.graph = defaultdict(list)

    # function to add an edge to graph
    def addEdge(self, u, v):
        self.graph[u].append(v)

    # A function used by DFS
    def DFSUtil(self, v, visited):
        # Mark the current node as visited and print it
        visited.add(v)
        print(v, end=" ")

        # Recur for all the vertices adjacent to this vertex
        for i in self.graph[v]:
            if i not in visited:
                self.DFSUtil(i, visited)

    # The function to do DFS traversal.
    def DFS(self):
        # Using a set for visited is more flexible than a fixed-size list
        visited = set()

        # Call the recursive helper function to print DFS traversal
        # starting from all vertices to handle disconnected graphs
        # We use list(self.graph) to get all keys/nodes
        for i in list(self.graph):
            if i not in visited:
                self.DFSUtil(i, visited)

# Driver code
g = Graph()
g.addEdge(0, 1)
g.addEdge(0, 2)
g.addEdge(1, 2)
g.addEdge(2, 0)
g.addEdge(2, 3)
g.addEdge(3, 3)

print("Following is Depth First Traversal:")
g.DFS()

# Graph dictionary representing the Romania Map
graph = {
    'Arad': {'Zerind': 75, 'Sibiu': 140, 'Timisoara': 118},
    'Zerind': {'Oradea': 71, 'Arad': 75},
    'Oradea': {'Sibiu': 151, 'Zerind': 71},
    'Sibiu': {'Arad': 140, 'Oradea': 151, 'Fagaras': 99, 'Rimnicu Vilcea': 80},
    'Timisoara': {'Arad': 118, 'Lugoj': 111},
    'Lugoj': {'Timisoara': 111, 'Mehadia': 70},
    'Mehadia': {'Lugoj': 70, 'Drobeta': 75},
    'Drobeta': {'Mehadia': 75, 'Craiova': 120},
    'Craiova': {'Drobeta': 120, 'Rimnicu Vilcea': 146, 'Pitesti': 138},
    'Rimnicu Vilcea': {'Sibiu': 80, 'Craiova': 146, 'Pitesti': 97},
    'Fagaras': {'Sibiu': 99, 'Bucharest': 211},
    'Pitesti': {'Rimnicu Vilcea': 97, 'Craiova': 138, 'Bucharest': 101},
    'Bucharest': {'Fagaras': 211, 'Pitesti': 101}
}

def dfs_tsp(graph, current, goal, visited, path, distance):
    path.append(current)
    visited.add(current)

    if current == goal:
        return path, distance

    for neighbor, weight in graph[current].items():
        if neighbor not in visited:
            result_path, total_dist = dfs_tsp(graph, neighbor, goal, visited, path[:], distance + weight)
            if result_path:
                return result_path, total_dist

    return None, 0

# Execution
start_node = 'Arad'
goal_node = 'Bucharest'
final_path, total_distance = dfs_tsp(graph, start_node, goal_node, set(), [], 0)

print(f"Following is the Depth-First Search Path from {start_node} to {goal_node}:")
print(" -> ".join(final_path))
print(f"Total Distance: {total_distance}")

def bfs_count(graph, start, goal):
    visited = []
    queue = [[start]]
    while queue:
        path = queue.pop(0)
        node = path[-1]
        if node not in visited:
            visited.append(node)
            if node == goal: return len(visited), path
            for neighbor in graph.get(node, {}):
                new_path = list(path)
                new_path.append(neighbor)
                queue.append(new_path)
    return len(visited), []

def dfs_count(graph, start, goal):
    visited = []
    stack = [[start]]
    while stack:
        path = stack.pop()
        node = path[-1]
        if node not in visited:
            visited.append(node)
            if node == goal: return len(visited), path
            # Reversed to simulate standard search order
            for neighbor in reversed(list(graph.get(node, {}).keys())):
                new_path = list(path)
                new_path.append(neighbor)
                stack.append(new_path)
    return len(visited), []

# Example Test for Case 1:
bfs_v, _ = bfs_count(graph, 'Arad', 'Timisoara')
dfs_v, _ = dfs_count(graph, 'Arad', 'Timisoara')
print(f"BFS visited: {bfs_v}, DFS visited: {dfs_v}")